### ISSUE TITLE
Seperate threshold for Start and Stop

### ISSUE THREAD

**Issue by twelve-cgn** [xoseperez/node-red-contrib-power-monitor#7]
Hi,
I want to build a monitoring system for the washing machine. However, due to the standby consumption, I need different values for start and stop.
Would be great if this could be implemented.

**Comment by DerJokerz** [comment]
Hello,

it's the same with me, I use the monitor for a washing machine, a dryer and a dishwasher.

For the dryer it works great, because the dryer runs 2-3 hrs and has a permanent power above 1 watt.

With the washing machine and dishwasher this is unfortunately different, they often have pauses between the individual washing programs, where they need 0-1 watt. Until it then continues, the monitor reports that the device is ready.

**Comment by xoseperez** [comment]
Added with v1.0.0
